image: microsoft/dotnet:latest
stages:
  - build
before_script:
  - curl -sL https://deb.nodesource.com/setup_5.x | bash -
  - apt-get install --yes nodejs
build:
  stage: build
  script:
    - bash build.sh
