image: microsoft/aspnet:1.0.0-rc1-update1
stages:
  - build
before_script:
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  - sudo apt-get install --yes nodejs
job1:
  stage: build
  script:
    - bash build.sh --quiet verify
  artifacts:
    paths:
      - src/*/bin/Debug/*.nupkg
