
var VERSION='0.1'
var FULL_VERSION='0.1'
var AUTHORS='Kasbah'

use-standard-lifecycle
k-standard-goals

#xml-docs-test .clean .build-compile description='Check generated XML documentation files for errors' target='package'
  k-xml-docs-test
